language: c
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_install:
  - sudo pip install cpp-coveralls
  - sudo pip3 install cffi
  - sudo pip3 install colorama
  - sudo pip3 install coloredlogs
  - sudo pip3 install docopt
  - sudo pip3 install terminaltables
script:
  - make tests
  - make test_virtraft
after_success:
  - coveralls --verbose --exclude include --exclude tests --exclude CLinkedListQueue
