name: CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Set up Python for testing
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install Python dependencies
      run:
        python -m pip install -r tests/requirements.txt
    - name: Run tests
      run:
        make tests_full
