#!/bin/bash
[ -d ./secret ] || mkdir secret
if [ -f ./secret/id_rsa ]; then
  echo "Keys already created; rm ./secret/* to recreate!"
  exit 1
 fi

ssh-keygen -t rsa -N "" -m PEM -f ./secret/id_rsa
(
echo "# File is auto-generated by genkeys.sh"
echo "AUTHORIZED_KEYS=$(cat ./secret/id_rsa.pub)"
# Only needed if using git+ssh
# echo "KNOWN_HOSTS=$(ssh-keyscan -t rsa github.com)"
echo "PRIVATE_KEY=$(cat ./secret/id_rsa | sed 's/$/\\n/g' | tr -d '\n')"
) > ./secret/keys.env
